version: '3.4'
services:
  backend:
    image: tjanas94/czatek-backend
    build:
      context: .
      dockerfile: docker/node/Dockerfile

  frontend-build:
    image: tjanas94/czatek-frontend-build
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      cache_from:
        - tjanas94/czatek-frontend-build
      target: build

  frontend-confd:
    image: tjanas94/czatek-frontend-confd
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      cache_from:
        - tjanas94/czatek-frontend-build
        - tjanas94/czatek-frontend-confd
      target: confd

  frontend:
    image: tjanas94/czatek-frontend
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      cache_from:
        - tjanas94/czatek-frontend-build
        - tjanas94/czatek-frontend-confd
        - tjanas94/czatek-frontend
