version: '2.2'
services:
  db:
    restart: always
    image: postgres:10-alpine
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    volumes:
     - db-data:/var/lib/postgresql/data
    env_file: .env

  backend:
    restart: always
    image: tjanas94/czatek-backend
    ports:
      - "${BACKEND_WEB_PORT:-3000}:3000"
    links:
      - db
    depends_on:
      - db
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  frontend:
    restart: always
    image: tjanas94/czatek-frontend
    ports:
      - "${FRONTEND_WEB_PORT:-80}:80"
      - "${FRONTEND_SSL_PORT:-443}:443"
    volumes:
      - "${FRONTEND_SSL_PATH:-./local/certs}:/etc/certs"
      - "${LETSENCRYPT_WELLKNOWN_PATH:-./local/webroot/.well-known}:/usr/src/app/.well-known"
    links:
      - backend
    env_file: .env

volumes:
  db-data:
